spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
  url: jdbc:h2:tcp://localhost/~/shoeactions
  username: sa
  password:
  driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql : true
---
spring:
  profiles: dev
server:
  port: 8000
logging:
  level:
    org.hibernate.SQL: debug